# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Battleship
version:      0.0401
version_from: lib/Games/Battleship.pm
installdirs:  site
requires:
    Carp:                          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
